# -*- coding: utf-8 -*-
"""PASSWORD BREAKER GAME.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zsHvI0fr410iEf5v2n489yz69tXZ_qlz
"""

#PASSWORD BREAKER GAME Your assignment is to create a Python program containing a “password breaker game” in which
#the user is asked to guess an unknown password as quickly as possible. This game is loosely
#inspired by the games Mastermind and Wordle

import random

passwords = ['about', 'after', 'again', 'below', 'could',
'every', 'first', 'found', 'great', 'house', 'large', 'learn',
'never', 'other', 'place', 'plant', 'point', 'right', 'small',
'sound', 'spell', 'still', 'study', 'their', 'there', 'these',
'thing', 'think', 'three', 'water', 'where', 'which', 'world',
'would', 'write']

print("Welcome to the password breaker game!")

while True:
  count=0
  #Choosing random word
  random_password = random.choice(passwords)
  #print(random_password)
  mode= input("which mode would you like to play on (easy/hard)? \n").lower()

  if mode == "easy":
      while True:
          #added .lower() to make inputs lower case
          guess = input("Enter a guess (or type 'quit' to give up): ").lower()

          if guess == "quit":
            print("The password was",random_password)
            break
          count= count + 1
          if random_password == guess:
              print("correct!",count, "guesses used")
              break
          else:
              common_letters = set(random_password).intersection(guess)
              print(len(common_letters), "letters correct.")


  elif mode == "hard":
    count1 = 0
    while count1 <5:
        guess = input("Enter a guess (or type 'quit' to give up): ").lower()

        if guess == "quit":
            print("The password was",random_password)
            break
        count1= count1 + 1

        if random_password == guess:
            print("correct!",count1, "guesses used")
            break
        else:
            common_letters = set(random_password).intersection(guess)
            print(len(common_letters), "letters correct.")
    if count1 == 5 :
            print("The correct password was:", random_password)
  else :
        print("Invalid mode, choose 'easy or 'hard'")

  again = input("do you want to play again?").lower()
  if again == "no":
    break